// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "prbs31.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic prbs31::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic prbs31::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> prbs31::ap_ST_fsm_state1 = "1";
const sc_lv<32> prbs31::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> prbs31::ap_const_lv1_1 = "1";
const sc_lv<32> prbs31::ap_const_lv32_1E = "11110";
const sc_lv<32> prbs31::ap_const_lv32_1B = "11011";

prbs31::prbs31(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_hw_out);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_5_fu_57_p3 );

    SC_METHOD(thread_hw_out_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_newbit_fu_47_p2);
    sensitive << ( tmp_fu_31_p3 );
    sensitive << ( tmp_1_fu_39_p3 );

    SC_METHOD(thread_tmp_1_fu_39_p3);
    sensitive << ( a );

    SC_METHOD(thread_tmp_2_fu_53_p1);
    sensitive << ( a );

    SC_METHOD(thread_tmp_5_cast_fu_65_p1);
    sensitive << ( tmp_5_fu_57_p3 );

    SC_METHOD(thread_tmp_5_fu_57_p3);
    sensitive << ( tmp_2_fu_53_p1 );
    sensitive << ( newbit_fu_47_p2 );

    SC_METHOD(thread_tmp_fu_31_p3);
    sensitive << ( a );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "1";
    a = "00000000000000000000000000000010";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "prbs31_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, hw_out, "(port)hw_out");
    sc_trace(mVcdFile, hw_out_ap_vld, "(port)hw_out_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, a, "a");
    sc_trace(mVcdFile, tmp_5_cast_fu_65_p1, "tmp_5_cast_fu_65_p1");
    sc_trace(mVcdFile, tmp_fu_31_p3, "tmp_fu_31_p3");
    sc_trace(mVcdFile, tmp_1_fu_39_p3, "tmp_1_fu_39_p3");
    sc_trace(mVcdFile, tmp_2_fu_53_p1, "tmp_2_fu_53_p1");
    sc_trace(mVcdFile, newbit_fu_47_p2, "newbit_fu_47_p2");
    sc_trace(mVcdFile, tmp_5_fu_57_p3, "tmp_5_fu_57_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("prbs31.hdltvin.dat");
    mHdltvoutHandle.open("prbs31.hdltvout.dat");
}

prbs31::~prbs31() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void prbs31::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        a = tmp_5_cast_fu_65_p1.read();
    }
}

void prbs31::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void prbs31::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void prbs31::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void prbs31::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void prbs31::thread_hw_out() {
    hw_out = esl_zext<32,31>(tmp_5_fu_57_p3.read());
}

void prbs31::thread_hw_out_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        hw_out_ap_vld = ap_const_logic_1;
    } else {
        hw_out_ap_vld = ap_const_logic_0;
    }
}

void prbs31::thread_newbit_fu_47_p2() {
    newbit_fu_47_p2 = (tmp_fu_31_p3.read() ^ tmp_1_fu_39_p3.read());
}

void prbs31::thread_tmp_1_fu_39_p3() {
    tmp_1_fu_39_p3 = a.read().range(27, 27);
}

void prbs31::thread_tmp_2_fu_53_p1() {
    tmp_2_fu_53_p1 = a.read().range(30-1, 0);
}

void prbs31::thread_tmp_5_cast_fu_65_p1() {
    tmp_5_cast_fu_65_p1 = esl_zext<32,31>(tmp_5_fu_57_p3.read());
}

void prbs31::thread_tmp_5_fu_57_p3() {
    tmp_5_fu_57_p3 = esl_concat<30,1>(tmp_2_fu_53_p1.read(), newbit_fu_47_p2.read());
}

void prbs31::thread_tmp_fu_31_p3() {
    tmp_fu_31_p3 = a.read().range(30, 30);
}

void prbs31::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

void prbs31::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"hw_out\" :  \"" << hw_out.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"hw_out_ap_vld\" :  \"" << hw_out_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

