// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _prbs31_HH_
#define _prbs31_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct prbs31 : public sc_module {
    // Port declarations 8
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<32> > hw_out;
    sc_out< sc_logic > hw_out_ap_vld;


    // Module declarations
    prbs31(sc_module_name name);
    SC_HAS_PROCESS(prbs31);

    ~prbs31();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > a;
    sc_signal< sc_lv<32> > tmp_5_cast_fu_65_p1;
    sc_signal< sc_lv<1> > tmp_fu_31_p3;
    sc_signal< sc_lv<1> > tmp_1_fu_39_p3;
    sc_signal< sc_lv<30> > tmp_2_fu_53_p1;
    sc_signal< sc_lv<1> > newbit_fu_47_p2;
    sc_signal< sc_lv<31> > tmp_5_fu_57_p3;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_state1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<32> ap_const_lv32_1B;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_hw_out();
    void thread_hw_out_ap_vld();
    void thread_newbit_fu_47_p2();
    void thread_tmp_1_fu_39_p3();
    void thread_tmp_2_fu_53_p1();
    void thread_tmp_5_cast_fu_65_p1();
    void thread_tmp_5_fu_57_p3();
    void thread_tmp_fu_31_p3();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
